import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

import StyledJsxRegistry from './registry'
import NextTopLoader from 'nextjs-toploader'
import { GluestackUIProvider } from 'app/components/ui/gluestack-ui-provider'
import { ReactNode } from 'react'
import  WebLayout  from 'app/layout/web'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" />
        <meta name="theme-color" content="#e0fe0e" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="#e0fe0e" />
        <meta name="apple-mobile-web-app-title" content="Pulse AI" />
        <meta name="msapplication-navbutton-color" content="#e0fe0e" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="#e0fe0e" />
        <link rel="manifest" href="../manifest.json" />
        <link rel="icon" href="/favicon.ico" sizes="any" />

        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body suppressHydrationWarning className={inter.className} style={{ display: 'flex' }}>
        <StyledJsxRegistry>
          <NextTopLoader
            color="#e0fe0e"
            initialPosition={0.08}
            crawlSpeed={200}
            height={4}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #707f07,0 0 5px #707f07"
            template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
            zIndex={1600}
            showAtBottom={false}
          />
          <GluestackUIProvider mode="light">
            <WebLayout>
            {children}
            </WebLayout>
          </GluestackUIProvider>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
